# Generated by Django 4.1.2 on 2022-10-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
