# Generated by Django 4.1.2 on 2022-11-01 10:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0003_chatroom_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='online',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
